/**
 * WASM Physics Engine exports
 */

// Core bridge functions
export {
  initPhysicsEngine,
  isPhysicsEngineInitialized,
  getPhysicsEngine,
  stepPhysics,
  stepAndSync,
  getWeatherModifiers,
  getAmbientConditions,
  // Weather API
  setCustomWeather,
  getRainIntensity,
  // Environment API
  setEnvironment,
  getAirDensity,
  getSurfaceFrictionBreakdown,
  // Wind API
  setWind,
  setWindEnabled,
  isWindEnabled,
  getWindState,
  getWindModifiers,
  // Tire API
  setTireCompound,
  getTireCompound,
  getTireWear,
  resetTireWear,
  getEffectiveGrip,
  getBoostPressureBar,
  getFuelMassKg,
  getFuelFlowFactor,
  setFuelMassKg,
  getFuelMixMode,
  setFuelMixMode,
  setOnCurb,
  isOnCurb,
  setSurface,
  getSurface,
  isOnRoad,
  isOffTrack,
  getSurfaceModifiers,
  getTrackCellCount,
  updateCarDriving,
  // Road temperature API
  setRoadCell,
  setRoadRegion,
  // Water depth
  getWaterDepth,
  getActiveSurfaceCells,
  getDebugState,
  createDefaultInput,
  inputFromKeyboard,
  TireCompound,
  SurfaceType,
  // ERS API
  setErsMode,
  getErsMode,
  getErsBatteryCharge,
  setErsBatteryCharge,
  setErsOvertakeAvailable,
  getErsState,
  // Semi-Auto ERS API
  setErsSemiAutoPreset,
  getErsSemiAutoPreset,
  getErsSemiAutoConfig,
  setErsLapMode,
  setErsExpertMode,
  activateErsOvertake,
  deactivateErsOvertake,
  isErsOvertakeOverride,
  // Active Aero API
  setAeroMode,
  getAeroMode,
  getActiveAeroState,
  toggleAeroAuto,
  setDrsZone,
  disableDrsOnBrake,
  resetErsLap,
  // Brake System API
  setBrakeBias,
  getBrakeBias,
  increaseBrakeBias,
  decreaseBrakeBias,
  setEngineBrakingLevel,
  getEngineBrakingLevel,
  cycleEngineBrakingLevel,
  getBrakeState,
  // Terrain API
  initTerrain,
  setTerrainCell,
  setTerrainRegion,
  setTerrainHeight,
  queryTerrain,
  isTerrainInitialized,
  loadTerrainHeightmap,
  clearTerrain,
} from './PhysicsBridge'

export type {
  CarInput,
  CarPhysicsOutput,
  GripBreakdown,
  TireMaterialOutput,
  SurfaceFrictionBreakdown,
  WeatherModifiers,
  SurfaceModifiers,
  AmbientConditions,
  WindState,
  WindModifiers,
  ErsMode,
  ErsState,
  HarvestSource,
  SemiAutoPreset,
  SemiAutoConfig,
  SemiAutoState,
  AeroMode,
  ActiveAeroState,
  EngineBrakingLevel,
  BrakeState,
  FuelMixMode,
  StepAndSyncOutput,
  TerrainQueryResult,
  TerrainMaterialProperties,
  TerrainMaterial,
  PerWheelTerrain,
  BottomingOutState,
} from './PhysicsBridge'

// React provider
export { PhysicsProvider, usePhysics, usePhysicsOptional } from './PhysicsProvider'
