export const TELEMETRY_STRIDE = 40

export const CH = {
  TIMESTAMP: 0,
  DISTANCE: 1,
  SPEED_KMH: 2,
  THROTTLE: 3,
  BRAKE: 4,
  STEER: 5,
  GEAR: 6,
  RPM: 7,
  LATERAL_G: 8,
  LONGITUDINAL_G: 9,
  SLIP_ANGLE: 10,
  EFFECTIVE_GRIP: 11,
  DOWNFORCE_N: 12,
  ERS_BATTERY: 13,
  ERS_POWER_FLOW: 14,
  POS_X: 15,
  POS_Y: 16,
  POS_Z: 17,
  FORWARD_SPEED_MS: 18,
  IS_DRIFTING: 19,
  SKID_INTENSITY: 20,
  TIRE_WEAR_FL: 21,
  TIRE_WEAR_FR: 22,
  TIRE_WEAR_RL: 23,
  TIRE_WEAR_RR: 24,
  BRAKE_TEMP_FL: 25,
  BRAKE_TEMP_FR: 26,
  BRAKE_TEMP_RL: 27,
  BRAKE_TEMP_RR: 28,
  BRAKE_FADE: 29,
  AERO_MODE: 30,
  WING_FRONT: 31,
  WING_REAR: 32,
  ENGINE_TEMP: 33,
  TIRE_TEMP_FL: 34,
  TIRE_TEMP_FR: 35,
  TIRE_TEMP_RL: 36,
  TIRE_TEMP_RR: 37,
  STEER_ANGLE_DEG: 38,
  YAW_RATE: 39,
} as const

export type ChannelId = (typeof CH)[keyof typeof CH]

export interface ChannelMeta {
  name: string
  unit: string
  min: number
  max: number
}

export const CHANNEL_META: Record<ChannelId, ChannelMeta> = {
  [CH.TIMESTAMP]: { name: 'Time', unit: 'ms', min: 0, max: 120000 },
  [CH.DISTANCE]: { name: 'Distance', unit: 'm', min: 0, max: 10000 },
  [CH.SPEED_KMH]: { name: 'Speed', unit: 'km/h', min: 0, max: 380 },
  [CH.THROTTLE]: { name: 'Throttle', unit: '', min: 0, max: 1 },
  [CH.BRAKE]: { name: 'Brake', unit: '', min: 0, max: 1 },
  [CH.STEER]: { name: 'Steer', unit: '', min: -1, max: 1 },
  [CH.GEAR]: { name: 'Gear', unit: '', min: -1, max: 8 },
  [CH.RPM]: { name: 'RPM', unit: 'rpm', min: 0, max: 15000 },
  [CH.LATERAL_G]: { name: 'Lateral G', unit: 'G', min: -6, max: 6 },
  [CH.LONGITUDINAL_G]: { name: 'Long G', unit: 'G', min: -6, max: 6 },
  [CH.SLIP_ANGLE]: { name: 'Slip Angle', unit: 'rad', min: -1, max: 1 },
  [CH.EFFECTIVE_GRIP]: { name: 'Grip', unit: '', min: 0, max: 1 },
  [CH.DOWNFORCE_N]: { name: 'Downforce', unit: 'N', min: 0, max: 30000 },
  [CH.ERS_BATTERY]: { name: 'ERS Battery', unit: '%', min: 0, max: 100 },
  [CH.ERS_POWER_FLOW]: { name: 'ERS Power', unit: 'kW', min: -200, max: 200 },
  [CH.POS_X]: { name: 'Pos X', unit: 'm', min: -1000, max: 1000 },
  [CH.POS_Y]: { name: 'Pos Y', unit: 'm', min: -100, max: 100 },
  [CH.POS_Z]: { name: 'Pos Z', unit: 'm', min: -1000, max: 1000 },
  [CH.FORWARD_SPEED_MS]: { name: 'Fwd Speed', unit: 'm/s', min: 0, max: 100 },
  [CH.IS_DRIFTING]: { name: 'Drifting', unit: '', min: 0, max: 1 },
  [CH.SKID_INTENSITY]: { name: 'Skid', unit: '', min: 0, max: 1 },
  [CH.TIRE_WEAR_FL]: { name: 'Wear FL', unit: '', min: 0, max: 1 },
  [CH.TIRE_WEAR_FR]: { name: 'Wear FR', unit: '', min: 0, max: 1 },
  [CH.TIRE_WEAR_RL]: { name: 'Wear RL', unit: '', min: 0, max: 1 },
  [CH.TIRE_WEAR_RR]: { name: 'Wear RR', unit: '', min: 0, max: 1 },
  [CH.BRAKE_TEMP_FL]: { name: 'Brake °C FL', unit: '°C', min: 0, max: 1200 },
  [CH.BRAKE_TEMP_FR]: { name: 'Brake °C FR', unit: '°C', min: 0, max: 1200 },
  [CH.BRAKE_TEMP_RL]: { name: 'Brake °C RL', unit: '°C', min: 0, max: 1200 },
  [CH.BRAKE_TEMP_RR]: { name: 'Brake °C RR', unit: '°C', min: 0, max: 1200 },
  [CH.BRAKE_FADE]: { name: 'Brake Fade', unit: '', min: 0, max: 1 },
  [CH.AERO_MODE]: { name: 'Aero Mode', unit: '', min: 0, max: 1 },
  [CH.WING_FRONT]: { name: 'Front Wing', unit: '', min: 0, max: 1 },
  [CH.WING_REAR]: { name: 'Rear Wing', unit: '', min: 0, max: 1 },
  [CH.ENGINE_TEMP]: { name: 'Engine Temp', unit: '', min: 0, max: 1 },
  [CH.TIRE_TEMP_FL]: { name: 'Tire Temp FL', unit: '', min: 0, max: 1 },
  [CH.TIRE_TEMP_FR]: { name: 'Tire Temp FR', unit: '', min: 0, max: 1 },
  [CH.TIRE_TEMP_RL]: { name: 'Tire Temp RL', unit: '', min: 0, max: 1 },
  [CH.TIRE_TEMP_RR]: { name: 'Tire Temp RR', unit: '', min: 0, max: 1 },
  [CH.STEER_ANGLE_DEG]: { name: 'Steer Angle', unit: '°', min: -25, max: 25 },
  [CH.YAW_RATE]: { name: 'Yaw Rate', unit: 'rad/s', min: -2, max: 2 },
}
