/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestModeRouteImport } from './routes/test-mode'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTrackPreviewRouteImport } from './routes/_authed/track-preview'
import { Route as AuthedTrackEditorRouteImport } from './routes/_authed/track-editor'
import { Route as AuthedShowroomRouteImport } from './routes/_authed/showroom'
import { Route as AuthedAccountRouteImport } from './routes/_authed/account'
import { Route as AuthedTrackPreviewIndexRouteImport } from './routes/_authed/track-preview.index'
import { Route as AuthedTrackPreviewPresetIdRouteImport } from './routes/_authed/track-preview.$presetId'
import { Route as AuthedTrackEditorTrackIdRouteImport } from './routes/_authed/track-editor.$trackId'
import { Route as AuthedRaceTrackIdRouteImport } from './routes/_authed/race.$trackId'

const TestModeRoute = TestModeRouteImport.update({
  id: '/test-mode',
  path: '/test-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTrackPreviewRoute = AuthedTrackPreviewRouteImport.update({
  id: '/track-preview',
  path: '/track-preview',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrackEditorRoute = AuthedTrackEditorRouteImport.update({
  id: '/track-editor',
  path: '/track-editor',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedShowroomRoute = AuthedShowroomRouteImport.update({
  id: '/showroom',
  path: '/showroom',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountRoute = AuthedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTrackPreviewIndexRoute = AuthedTrackPreviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedTrackPreviewRoute,
} as any)
const AuthedTrackPreviewPresetIdRoute =
  AuthedTrackPreviewPresetIdRouteImport.update({
    id: '/$presetId',
    path: '/$presetId',
    getParentRoute: () => AuthedTrackPreviewRoute,
  } as any)
const AuthedTrackEditorTrackIdRoute =
  AuthedTrackEditorTrackIdRouteImport.update({
    id: '/$trackId',
    path: '/$trackId',
    getParentRoute: () => AuthedTrackEditorRoute,
  } as any)
const AuthedRaceTrackIdRoute = AuthedRaceTrackIdRouteImport.update({
  id: '/race/$trackId',
  path: '/race/$trackId',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-mode': typeof TestModeRoute
  '/account': typeof AuthedAccountRoute
  '/showroom': typeof AuthedShowroomRoute
  '/track-editor': typeof AuthedTrackEditorRouteWithChildren
  '/track-preview': typeof AuthedTrackPreviewRouteWithChildren
  '/race/$trackId': typeof AuthedRaceTrackIdRoute
  '/track-editor/$trackId': typeof AuthedTrackEditorTrackIdRoute
  '/track-preview/$presetId': typeof AuthedTrackPreviewPresetIdRoute
  '/track-preview/': typeof AuthedTrackPreviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-mode': typeof TestModeRoute
  '/account': typeof AuthedAccountRoute
  '/showroom': typeof AuthedShowroomRoute
  '/track-editor': typeof AuthedTrackEditorRouteWithChildren
  '/race/$trackId': typeof AuthedRaceTrackIdRoute
  '/track-editor/$trackId': typeof AuthedTrackEditorTrackIdRoute
  '/track-preview/$presetId': typeof AuthedTrackPreviewPresetIdRoute
  '/track-preview': typeof AuthedTrackPreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/test-mode': typeof TestModeRoute
  '/_authed/account': typeof AuthedAccountRoute
  '/_authed/showroom': typeof AuthedShowroomRoute
  '/_authed/track-editor': typeof AuthedTrackEditorRouteWithChildren
  '/_authed/track-preview': typeof AuthedTrackPreviewRouteWithChildren
  '/_authed/race/$trackId': typeof AuthedRaceTrackIdRoute
  '/_authed/track-editor/$trackId': typeof AuthedTrackEditorTrackIdRoute
  '/_authed/track-preview/$presetId': typeof AuthedTrackPreviewPresetIdRoute
  '/_authed/track-preview/': typeof AuthedTrackPreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/test-mode'
    | '/account'
    | '/showroom'
    | '/track-editor'
    | '/track-preview'
    | '/race/$trackId'
    | '/track-editor/$trackId'
    | '/track-preview/$presetId'
    | '/track-preview/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/test-mode'
    | '/account'
    | '/showroom'
    | '/track-editor'
    | '/race/$trackId'
    | '/track-editor/$trackId'
    | '/track-preview/$presetId'
    | '/track-preview'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/test-mode'
    | '/_authed/account'
    | '/_authed/showroom'
    | '/_authed/track-editor'
    | '/_authed/track-preview'
    | '/_authed/race/$trackId'
    | '/_authed/track-editor/$trackId'
    | '/_authed/track-preview/$presetId'
    | '/_authed/track-preview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  TestModeRoute: typeof TestModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-mode': {
      id: '/test-mode'
      path: '/test-mode'
      fullPath: '/test-mode'
      preLoaderRoute: typeof TestModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/track-preview': {
      id: '/_authed/track-preview'
      path: '/track-preview'
      fullPath: '/track-preview'
      preLoaderRoute: typeof AuthedTrackPreviewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/track-editor': {
      id: '/_authed/track-editor'
      path: '/track-editor'
      fullPath: '/track-editor'
      preLoaderRoute: typeof AuthedTrackEditorRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/showroom': {
      id: '/_authed/showroom'
      path: '/showroom'
      fullPath: '/showroom'
      preLoaderRoute: typeof AuthedShowroomRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/account': {
      id: '/_authed/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthedAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/track-preview/': {
      id: '/_authed/track-preview/'
      path: '/'
      fullPath: '/track-preview/'
      preLoaderRoute: typeof AuthedTrackPreviewIndexRouteImport
      parentRoute: typeof AuthedTrackPreviewRoute
    }
    '/_authed/track-preview/$presetId': {
      id: '/_authed/track-preview/$presetId'
      path: '/$presetId'
      fullPath: '/track-preview/$presetId'
      preLoaderRoute: typeof AuthedTrackPreviewPresetIdRouteImport
      parentRoute: typeof AuthedTrackPreviewRoute
    }
    '/_authed/track-editor/$trackId': {
      id: '/_authed/track-editor/$trackId'
      path: '/$trackId'
      fullPath: '/track-editor/$trackId'
      preLoaderRoute: typeof AuthedTrackEditorTrackIdRouteImport
      parentRoute: typeof AuthedTrackEditorRoute
    }
    '/_authed/race/$trackId': {
      id: '/_authed/race/$trackId'
      path: '/race/$trackId'
      fullPath: '/race/$trackId'
      preLoaderRoute: typeof AuthedRaceTrackIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedTrackEditorRouteChildren {
  AuthedTrackEditorTrackIdRoute: typeof AuthedTrackEditorTrackIdRoute
}

const AuthedTrackEditorRouteChildren: AuthedTrackEditorRouteChildren = {
  AuthedTrackEditorTrackIdRoute: AuthedTrackEditorTrackIdRoute,
}

const AuthedTrackEditorRouteWithChildren =
  AuthedTrackEditorRoute._addFileChildren(AuthedTrackEditorRouteChildren)

interface AuthedTrackPreviewRouteChildren {
  AuthedTrackPreviewPresetIdRoute: typeof AuthedTrackPreviewPresetIdRoute
  AuthedTrackPreviewIndexRoute: typeof AuthedTrackPreviewIndexRoute
}

const AuthedTrackPreviewRouteChildren: AuthedTrackPreviewRouteChildren = {
  AuthedTrackPreviewPresetIdRoute: AuthedTrackPreviewPresetIdRoute,
  AuthedTrackPreviewIndexRoute: AuthedTrackPreviewIndexRoute,
}

const AuthedTrackPreviewRouteWithChildren =
  AuthedTrackPreviewRoute._addFileChildren(AuthedTrackPreviewRouteChildren)

interface AuthedRouteChildren {
  AuthedAccountRoute: typeof AuthedAccountRoute
  AuthedShowroomRoute: typeof AuthedShowroomRoute
  AuthedTrackEditorRoute: typeof AuthedTrackEditorRouteWithChildren
  AuthedTrackPreviewRoute: typeof AuthedTrackPreviewRouteWithChildren
  AuthedRaceTrackIdRoute: typeof AuthedRaceTrackIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountRoute: AuthedAccountRoute,
  AuthedShowroomRoute: AuthedShowroomRoute,
  AuthedTrackEditorRoute: AuthedTrackEditorRouteWithChildren,
  AuthedTrackPreviewRoute: AuthedTrackPreviewRouteWithChildren,
  AuthedRaceTrackIdRoute: AuthedRaceTrackIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  TestModeRoute: TestModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
