export const styles: Record<string, React.CSSProperties> = {
  container: {
    position: 'relative',
    zIndex: 1000,
  },
  dropdownButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 16px',
    background: 'rgba(0, 0, 0, 0.8)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: 8,
    color: '#fff',
    cursor: 'pointer',
    fontSize: 14,
    fontWeight: 500,
    minWidth: 180,
    transition: 'all 0.2s ease',
  },
  dropdownButtonHover: {
    borderColor: 'rgba(255, 255, 255, 0.4)',
    background: 'rgba(0, 0, 0, 0.9)',
  },
  trackName: {
    flex: 1,
    textAlign: 'left' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  arrow: {
    fontSize: 10,
    opacity: 0.7,
    transition: 'transform 0.2s ease',
  },
  arrowOpen: {
    transform: 'rotate(180deg)',
  },
  menu: {
    position: 'absolute' as const,
    top: 'calc(100% + 4px)',
    left: 0,
    minWidth: 250,
    background: 'rgba(0, 0, 0, 0.95)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: 8,
    overflow: 'hidden',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
  },
  menuSection: {
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
  },
  menuSectionTitle: {
    padding: '8px 12px',
    fontSize: 10,
    textTransform: 'uppercase' as const,
    color: '#666',
    fontWeight: 600,
  },
  menuItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 12px',
    color: '#fff',
    cursor: 'pointer',
    transition: 'background 0.15s ease',
    fontSize: 13,
  },
  menuItemActive: {
    background: 'rgba(59, 130, 246, 0.3)',
  },
  menuItemHover: {
    background: 'rgba(255, 255, 255, 0.1)',
  },
  menuItemIcon: {
    width: 18,
    textAlign: 'center' as const,
    opacity: 0.7,
  },
  menuItemName: {
    flex: 1,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap' as const,
  },
  menuItemMeta: {
    fontSize: 11,
    color: '#666',
  },
  actionButton: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    width: '100%',
    padding: '10px 12px',
    border: 'none',
    background: 'transparent',
    color: '#fff',
    cursor: 'pointer',
    transition: 'background 0.15s ease',
    fontSize: 13,
    textAlign: 'left' as const,
  },
  actionButtonDanger: {
    color: '#ef4444',
  },
  input: {
    width: '100%',
    padding: '8px 12px',
    margin: '0 12px 12px',
    background: 'rgba(255, 255, 255, 0.1)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: 6,
    color: '#fff',
    fontSize: 13,
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  confirmButtons: {
    display: 'flex',
    gap: 8,
    padding: '8px 12px',
  },
  confirmButton: {
    flex: 1,
    padding: '6px 12px',
    border: 'none',
    borderRadius: 4,
    cursor: 'pointer',
    fontSize: 12,
    fontWeight: 600,
  },
  confirmButtonPrimary: {
    background: '#3b82f6',
    color: '#fff',
  },
  confirmButtonSecondary: {
    background: 'rgba(255, 255, 255, 0.1)',
    color: '#fff',
  },
  confirmButtonDanger: {
    background: '#ef4444',
    color: '#fff',
  },
  noTracks: {
    padding: '20px 12px',
    textAlign: 'center' as const,
    color: '#666',
    fontSize: 13,
  },
}
