export const styles: Record<string, React.CSSProperties> = {
  backdrop: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    pointerEvents: 'auto',
    zIndex: 1000,
  },
  modal: {
    background: 'rgba(20, 20, 20, 0.95)',
    borderRadius: 12,
    padding: '24px 32px',
    minWidth: 360,
    maxWidth: '90vw',
    border: '1px solid rgba(255, 255, 255, 0.1)',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.4)',
  },
  title: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 20,
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 11,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
    borderBottom: '1px solid rgba(255, 255, 255, 0.1)',
    paddingBottom: 4,
  },
  sliderRow: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  sliderHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sliderLabel: {
    color: '#fff',
    fontSize: 13,
  },
  sliderValue: {
    color: '#4CAF50',
    fontSize: 13,
    fontFamily: 'monospace',
  },
  slider: {
    width: '100%',
    height: 6,
    WebkitAppearance: 'none',
    appearance: 'none',
    background: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 3,
    outline: 'none',
    cursor: 'pointer',
  },
  sliderDescription: {
    color: 'rgba(255, 255, 255, 0.5)',
    fontSize: 11,
    textAlign: 'right',
  },
  compassContainer: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 12,
  },
  compass: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 40px)',
    gridTemplateRows: 'repeat(3, 40px)',
    gap: 4,
  },
  compassButton: {
    width: 40,
    height: 40,
    background: 'rgba(255, 255, 255, 0.1)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: 6,
    color: '#fff',
    fontSize: 11,
    fontWeight: 'bold',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.2s ease',
  },
  compassButtonActive: {
    background: '#4CAF50',
    border: '1px solid #4CAF50',
  },
  compassCenter: {
    background: 'transparent',
    border: 'none',
    cursor: 'default',
  },
  toggleRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 0',
  },
  toggleLabel: {
    color: '#fff',
    fontSize: 13,
  },
  toggle: {
    width: 44,
    height: 24,
    background: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    position: 'relative',
    cursor: 'pointer',
    transition: 'background 0.2s ease',
  },
  toggleActive: {
    background: '#4CAF50',
  },
  toggleKnob: {
    width: 18,
    height: 18,
    background: '#fff',
    borderRadius: '50%',
    position: 'absolute',
    top: 3,
    left: 3,
    transition: 'left 0.2s ease',
  },
  toggleKnobActive: {
    left: 23,
  },
  closeButton: {
    width: '100%',
    marginTop: 16,
    padding: '10px 20px',
    background: 'rgba(255, 255, 255, 0.1)',
    border: '1px solid rgba(255, 255, 255, 0.2)',
    borderRadius: 6,
    color: '#fff',
    fontSize: 13,
    cursor: 'pointer',
    transition: 'background 0.2s ease',
  },
  hint: {
    textAlign: 'center',
    fontSize: 11,
    color: 'rgba(255, 255, 255, 0.4)',
    marginTop: 12,
  },
}

export const COMPASS_GRID = [
  ['NW', 'N', 'NE'],
  ['W', null, 'E'],
  ['SW', 'S', 'SE'],
] as const
