name = "car-api"
main = "src/index.ts"
compatibility_date = "2026-05-01"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
# Non-secret config goes here.
# Secrets: use `wrangler secret put <NAME>` for prod; `.dev.vars` for local dev.

[[d1_databases]]
binding = "DB"
database_name = "car-auth"
database_id = "813cc652-95c2-418d-a4b5-c918625af3b6"

[[kv_namespaces]]
binding = "SESSIONS"
id = "9816cae642644d128f06301782ea9a53"
